var timeAct=360; timeIni=360; timeBon=0;
var successes=0; successesMax=5; attempts=0; attemptsMax=1;
var score=0; scoreMax=5; scoreInc=1; scoreDec=1
var typeGame=0;
var tiTime=false;
var tiTimeType=2;
var tiButtonTime=true;
var textButtonTime="Comenzar";
var tiSuccesses=true;
var tiAttempts=false;
var tiScore=false;
var startTime;
var colorBack="#FFFDFD"; colorButton="#FF8000"; colorText="#000000"; colorSele="#A0A0A4";
var goURLNext=false; goURLRepeat=false;tiAval=false;
var scoOk=0; scoWrong=0; scoOkDo=0; scoWrongDo=0; scoMessage=""; scoPtos=10;
var fMenssage="Arial, Helvetica, sans-serif";
var fActi="Arial, Helvetica, sans-serif";
var fEnun="Arial, Helvetica, sans-serif";
var timeOnMessage=2; messageOk="Optime!!"; messageTime=""; messageError="Me paenitet. Falsum est!"; messageErrorG="Me paenitet. Falsum est!"; messageAttempts=""; isShowMessage=false;
var urlOk=""; urlTime=""; urlError=""; urlAttempts="";
var goURLOk="_blank"; goURLTime="_blank"; goURLAttempts="_blank"; goURLError="_blank"; 
borderOk="#0000FF"; borderTime="#FF0000";borderError="#FF0000"; borderAttempts="#FF0000";
var wordsGame="MDEuMDMuMDYuT3JkZW5hcl9GcmFzZXM"; wordsStr = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";
function giveZindex(typeElement){var valueZindex=0; capas=document.getElementsByTagName(typeElement);
for (i=0;i<capas.length;i++){if (parseInt($(capas[i]).css("z-index"),10)>valueZindex){valueZindex=parseInt($(capas[i]).css("z-index"),10);}}return valueZindex;}
var words=["UXVpZCBlc3QgU3BhcnRhPyBPcHBpZHVtIHBhcnV1bSBlc3Qu","VmJpIHBhdWNpIGZsdXVpaSBzdW50PyBJbiBBcmFiaWEgcGF1Y2kgZmx1dWlpIHN1bnQu","TnVtIENyZXRhIGluc3VsYSBwYXJ1YSBlc3Q/IE5vbiwgQ3JldGEgaW5zdWxhIG1hZ25hIGVzdC4","RXN0bmUgSUkgbnVtZXJ1cyBtYWdudXM/IE5vbiwgSUkgbnVtZXJ1cyBwYXJ1dXMgZXN0Lg","UXVpZCBlc3QgSUlJPyBOdW1lcnVzIHJvbWFudXMgZXN0Lg"];imaW=["Oppidum.jpg","Arabia.jpg","Insula.jpg","DVO.001.jpg","TRES.001.jpg"];queW=["","","","",""]; c=[36,51,56,52,34];
var auW=["","","","",""];
var actMaxWidth="600"; actMaxHeight="400";indexG=0;profG=0;dirMedia="01.03.06.Ordenar_Frases_resources/media/"; textBNext="";
var wordsG=[];imageW=[];questionW=[];audioW=[];cG=[];
colorText="#000000";colorButton="#3399FF";colorBack="#FFFFFF";colorSele="#B6B6B6";goURLNext=true;goURLRepeat=true;
fMenssage="Verdana, Geneva, sans-serif";fActi="Verdana, Geneva, sans-serif";fEnun="Verdana, Geneva, sans-serif";
